### ISSUE TITLE
2021-08-20 ipfs.io outage Post Mortem Tracking issue

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs#469]
The purpose of this issue is to publicly track the various action items we're taking as a result of the 2021-08-20 ipfs.io outage: https://blog.ipfs.io/2021-08-27-IPFS.io-gateway-outage-resolution/

* [x] Reduce the blast radius by separating the IPFS website from the ipfs.io gateway onto different domains.  (see https://github.com/protocol/bifrost-infra/issues/178 )
* [ ] Reduce the time to respond by paging engineers on sustained gateway inaccessibility.
* [ ] Reduce time to mitigation by establishing and documenting direct human lines of communication for the registrars of domains of gateways operated by Protocol Labs.
* [ ] Reduce the likelihood of a complete domain takedown by making it even easier for a concerned party to contact us directly about objectionable content (beyond our pre-existing abuse takedown email and resources on the  Gateway FAQ and ipfs.io/legal, we will also publish and monitor email addresses in our domain records and ensure the root websites of our gateway domains provide links to our content policies. ).
* [ ] Reduce recovery time by simplifying and better documenting the custom DNS resolution on our gateways.

**Comment by BigLep** [comment]
The blog post for this event is being published via https://github.com/ipfs/ipfs-blog/pull/309

**Comment by BigLep** [comment]
For reference the notes that were used to generate the public blog post and the list of action items is here: https://www.notion.so/pl-strflt/2021-08-20-ipfs-io-outage-Post-Mortem-d3937d6992fc4822be554807209f5fb9

**Comment by BigLep** [comment]
2023-01-02 update: I know the first action item was completed.  I haven't checked with infra and techops on the latest for the other items.  I'm not currently able to chase this.

@andyschwab and @JesseXie are you able to verify here?  Internal tracking of items was here: https://www.notion.so/pl-strflt/2021-08-20-ipfs-io-outage-Post-Mortem-d3937d6992fc4822be554807209f5fb9#56155b871db14a699f7e51afe375a866

**Comment by andyschwab** [comment]
Items 3 & 4 are being tracked by RSS. More to come this quarter.
